


ARTIFACTS_DIR = 'artifacts'
LOGS_DIR = 'logs'
LOGS_FILE_NAME = 'xray.log'

BUCKET_NAME = 'lungxray'
ZIP_FILE_NAME = 'chest_xray.zip'
CLASS_LABEL_1 = 'NORMAL'
CLASS_LABEL_2 = 'PNEUMONIA'
RAW_FILE_NAME = 'chest_xray'



DATA_INGESTION_ARTIFACTS_DIR = 'DataIngestionArtifacts'
DATA_INGESTION_TRAIN_DIR = 'Train'
DATA_INGESTION_TEST_DIR = 'Test'
PARAMS_TEST_RATIO = 0.2